"""empty message

Revision ID: 7b5e73d9c507
Revises: c73176ac82d3
Create Date: 2026-01-03 16:25:25.854683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5e73d9c507'
down_revision: Union[str, Sequence[str], None] = 'c73176ac82d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        ALTER TABLE employees
        ALTER COLUMN hashed_password
        TYPE BYTEA
        USING hashed_password::bytea
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'hashed_password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
